# Generated by Django 3.2.6 on 2021-09-09 00:56

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_name, verbose_name='Imagem'),
        ),
    ]
