# Generated by Django 3.2.6 on 2021-09-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('funcionalidade', models.CharField(max_length=50, verbose_name='Funcionalidade')),
                ('descricao', models.TextField(max_length=80, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Telefone'), ('lni-cog', 'Engrenagem'), ('lni-leaf', 'Folha'), ('lni-layers', 'Papel')], max_length=16, verbose_name='Icone')),
                ('lado', models.CharField(choices=[('fadeInRight', 'Direita'), ('fadeInLeft', 'Esquerda')], max_length=11, verbose_name='Lado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
